var express = require('express')
var router = express.Router()

var authRouter = require('./auth')
var contactRouter = require('./contact')
var gamesRouter = require('./games')
var roomRouter = require('./room')
var searchRouter = require('./search')
var profileRouter = require('./profile_routes')
var ImageUploadRouter = require('./MongoImages')
var profile_friends_routes = require('./profile_friends_routes')
var notificationRoutes = require('./notificationRoutes')

router.use('/auth', authRouter)
router.use('/contact', contactRouter)
router.use('/games', gamesRouter)
router.use('/room', roomRouter)
router.use('/search', searchRouter)
router.use('/profiles', profileRouter)
router.use('/profile/img', ImageUploadRouter)
router.use('/friends_profiles', profile_friends_routes)
router.use('/notifications', notificationRoutes)
module.exports = router
